export interface Book {
  id: string
  title: string
  author: string
  cover: string
  genres: string[]
  rating?: number
  review?: string
  whyReading?: string
  year?: number
  status: 'reading' | 'done' | 'backlog'
  series?: string
  seriesNumber?: number
  startDate?: string
}

export const books: Book[] = [
  // --- CURRENTLY READING ---
  {
    id: 'scar-tissue',
    title: 'Scar Tissue',
    author: 'Anthony Kiedis & Larry Sloman',
    cover: '/static/scar_tissue.jpg',
    genres: ['Biography'],
    status: 'reading',
    year: 2026,
    whyReading: 'RHCP is one of my favorite bands of all-time. Heard Anthony\'s early life & road to fame is interesting to say the least.',
  },
  {
    id: 'price-of-time',
    title: 'The Price of Time',
    author: 'Edward Chancellor',
    cover: '/static/the_price_of_time.jpg',
    genres: ['Non-fiction'],
    status: 'reading',
    year: 2026,
    whyReading: 'It\'s about time for me to dive deep into what/how/why interest, you know?',
  },
  {
    id: 'ball-lightning',
    title: 'Ball Lightning',
    author: 'Cixin Liu',
    cover: '/static/ball_lightning.jpg',
    genres: ['Sci-Fi'],
    status: 'reading',
    year: 2026,
    whyReading: 'Who would of guessed, me reading a Cixin Liu book. Well this books plot seemed interesting to me...especially since it has to do with extreme weather.',
  },

  // --- DONE ---
  {
    id: 'atlas-extinct',
    title: 'An Atlas of Extinct Countries',
    author: 'Gideon Defoe',
    cover: '/static/atlas_of_extinct.jpg',
    genres: ['Non-fiction'],
    rating: 5,
    review: 'Very fun & quick read, maybe like a day or 2. It\'s also quick because it was super interesting to learn about these random countries that existed for like hours or even minutes lol. Defoe\'s writing style and humor is very enjoyable as well. FYI: Most of the failures of these countries is due to some King\'s son was trying to be relevant and then failed, rip.',
    status: 'done',
    year: 2024,
  },
  {
    id: 'well-of-ascension',
    title: 'Well of Ascension',
    author: 'Brandon Sanderson',
    cover: '/static/well_of_ascension.jpg',
    genres: ['Fantasy'],
    rating: 5,
    review: 'Wow... what a 2nd book for the triology. The rag-tag team that just overthrew the empire and Lord Ruler now having to face the consequences of actually dealing with the common peoples issues. Not only that, but having rival troops, Lords, and other Mistborn aiming at the city walls for dominance is a hell of a combination. Had a great time.',
    status: 'done',
    year: 2024,
    series: 'Mistborn',
    seriesNumber: 2,
  },
  {
    id: 'normal-people',
    title: 'Normal People',
    author: 'Sally Rooney',
    cover: '/static/normal-people.jpeg',
    genres: ['Fiction'],
    rating: 4,
    review: 'Hailey told me i needed to read this. I finally got it done while on our trip in Europe...and let me tell you... the story is well-written. The only reason I am giving 4/5 is due to the ending, left a bit to be explained.',
    status: 'done',
    year: 2024,
  },
  {
    id: 'to-hold-up-the-sky',
    title: 'To Hold Up The Sky',
    author: 'Cixin Liu',
    cover: '/static/to-hold-up-the-sky.jpeg',
    genres: ['Sci-Fi'],
    rating: 3,
    review: 'Short Stories but by Liu..., I need to read all his books tbh. But in the end, this one was a bit boring and did not do it for me.',
    status: 'done',
    year: 2023,
  },
  {
    id: 'creativity-code',
    title: 'The Creativity Code',
    author: 'Marcus du Sautoy',
    cover: '/static/the-creativity-code.jpeg',
    genres: ['Tech'],
    rating: 3,
    review: 'Interesting to get the Ai perspective *prior* the explosion of ChatGPT',
    status: 'done',
    year: 2023,
  },
  {
    id: 'mistborn',
    title: 'Mistborn',
    author: 'Brandon Sanderson',
    cover: '/static/mistborn.png',
    genres: ['Fantasy'],
    rating: 4,
    review: 'Sanderson makes a fantastic book with good fantasy (alchemy) and a great story with rebels fighting an unjust "Lord Ruler". Excited for the next 2 books in the triology',
    status: 'done',
    year: 2024,
    series: 'Mistborn',
    seriesNumber: 1,
  },
  {
    id: 'three-body-problem',
    title: 'The Three Body Problem',
    author: 'Cixin Liu',
    cover: '/static/three-body-problem.jpg',
    genres: ['Sci-Fi'],
    rating: 5,
    review: 'what an intro to this trilogy(RoEP). So much science and futuristic tech, while some serious morality issues being brought up',
    status: 'done',
    year: 2023,
    series: 'Remembrance of Earth\'s Past',
    seriesNumber: 1,
  },
  {
    id: 'dark-forest',
    title: 'The Dark Forest',
    author: 'Cixin Liu',
    cover: '/static/dark-forest.jpg',
    genres: ['Sci-Fi'],
    rating: 3,
    review: 'this one gets weird, but still good setup for final beast of a book. The whole series kind of asks the question: how would earth react if we know aliens are coming to invade in like 500 yrs',
    status: 'done',
    year: 2023,
    series: 'Remembrance of Earth\'s Past',
    seriesNumber: 2,
  },
  {
    id: 'deaths-end',
    title: "Death's End",
    author: 'Cixin Liu',
    cover: '/static/deaths-end.jpg',
    genres: ['Sci-Fi'],
    rating: 5,
    review: 'legit so wild, the ending still messes me up. great conclusion to probably my favorite trilogy ever. You get everything: sci-fi / aliens / engineering / war / love / morality / future human existence / alien-human interaction',
    status: 'done',
    year: 2023,
    series: 'Remembrance of Earth\'s Past',
    seriesNumber: 3,
  },
  {
    id: 'silent-patient',
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    cover: '/static/silent-patient.jpeg',
    genres: ['Mystery'],
    rating: 4,
    review: 'fast paced book, ending pretty wild, quick read',
    status: 'done',
    year: 2023,
  },
  {
    id: 'i-robot',
    title: 'iRobot',
    author: 'Isaac Asimov',
    cover: '/static/i-robot.jpeg',
    genres: ['Sci-Fi'],
    rating: 2,
    review: 'just eh, got stars from the sci-fi aspect alone, stories were a bit boring',
    status: 'done',
    year: 2023,
  },
  {
    id: 'goodbye-descartes',
    title: 'Goodbye Descartes',
    author: 'Keith Delvin',
    cover: '/static/goodbye-descartes.jpeg',
    genres: ['Non-fiction'],
    rating: 4,
    review: 'laws of thought and logic in the eyes of ancient Greeks. Interesting to read about what they thought about AI in the late 90\'s',
    status: 'done',
    year: 2023,
  },
  {
    id: 'even-greater-mistakes',
    title: 'Even Greater Mistakes',
    author: 'Charlie Jane Anders',
    cover: '/static/even-greater-mistakes.jpeg',
    genres: ['Sci-Fi'],
    rating: 2,
    review: '"the best sci-fi short stories" -people\n"most of the short stories are lame tbh" - me',
    status: 'done',
    year: 2023,
  },

  // --- BACKLOG ---
  {
    id: 'hero-of-ages',
    title: 'The Hero of Ages',
    author: 'Brandon Sanderson',
    cover: '/static/hero_of_ages.jpg',
    genres: ['Fantasy'],
    status: 'backlog',
    series: 'Mistborn',
    seriesNumber: 3,
  },
  {
    id: 'to-hell-with-hustle',
    title: 'To Hell with the Hustle',
    author: 'Jefferson Bethke',
    cover: '/static/to_hell_with_hustle.jpg',
    genres: ['Non-fiction'],
    status: 'backlog',
  },
  {
    id: 'elon-musk',
    title: 'Elon Musk',
    author: 'Walter Isaacson',
    cover: '/static/elon_musk.jpg',
    genres: ['Biography'],
    status: 'backlog',
  },
  {
    id: 'general-ignorance',
    title: 'The Book of General Ignorance',
    author: 'John Lloyd & John Mitchinson',
    cover: '/static/general_ignorance.jpg',
    genres: ['Non-fiction'],
    status: 'backlog',
  },
  {
    id: 'anxious-generation',
    title: 'The Anxious Generation',
    author: 'Jonathan Haidt',
    cover: '/static/the_anxious_gen.jpg',
    genres: ['Non-fiction'],
    status: 'backlog',
  },
]

export const GENRE_COLORS: Record<string, string> = {
  'Sci-Fi': '#0ea5e9',
  'Fantasy': '#8b5cf6',
  'Mystery': '#a78bfa',
  'Tech': '#10b981',
  'Non-fiction': '#f97316',
  'Fiction': '#ec4899',
  'Biography': '#06b6d4',
}

export const ALL_GENRES = Object.keys(GENRE_COLORS)
